#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class Button;
                ref class MediaElement;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace App2
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Image^ image;
        private: ::Windows::UI::Xaml::Controls::Image^ board;
        private: ::Windows::UI::Xaml::Controls::Image^ image11;
        private: ::Windows::UI::Xaml::Controls::Image^ image12;
        private: ::Windows::UI::Xaml::Controls::Image^ image13;
        private: ::Windows::UI::Xaml::Controls::Image^ image14;
        private: ::Windows::UI::Xaml::Controls::Image^ image15;
        private: ::Windows::UI::Xaml::Controls::Image^ image16;
        private: ::Windows::UI::Xaml::Controls::Image^ image17;
        private: ::Windows::UI::Xaml::Controls::Image^ image18;
        private: ::Windows::UI::Xaml::Controls::Image^ image19;
        private: ::Windows::UI::Xaml::Controls::Image^ image21;
        private: ::Windows::UI::Xaml::Controls::Image^ image22;
        private: ::Windows::UI::Xaml::Controls::Image^ image23;
        private: ::Windows::UI::Xaml::Controls::Image^ image24;
        private: ::Windows::UI::Xaml::Controls::Image^ image25;
        private: ::Windows::UI::Xaml::Controls::Image^ image26;
        private: ::Windows::UI::Xaml::Controls::Image^ image27;
        private: ::Windows::UI::Xaml::Controls::Image^ image28;
        private: ::Windows::UI::Xaml::Controls::Image^ image29;
        private: ::Windows::UI::Xaml::Controls::Button^ button0;
        private: ::Windows::UI::Xaml::Controls::Button^ button1;
        private: ::Windows::UI::Xaml::Controls::Button^ button2;
        private: ::Windows::UI::Xaml::Controls::Button^ button9;
        private: ::Windows::UI::Xaml::Controls::Button^ button21;
        private: ::Windows::UI::Xaml::Controls::Button^ button22;
        private: ::Windows::UI::Xaml::Controls::Button^ button23;
        private: ::Windows::UI::Xaml::Controls::Button^ button14;
        private: ::Windows::UI::Xaml::Controls::Button^ button4;
        private: ::Windows::UI::Xaml::Controls::Button^ button7;
        private: ::Windows::UI::Xaml::Controls::Button^ button16;
        private: ::Windows::UI::Xaml::Controls::Button^ button19;
        private: ::Windows::UI::Xaml::Controls::Button^ button20;
        private: ::Windows::UI::Xaml::Controls::Button^ button13;
        private: ::Windows::UI::Xaml::Controls::Button^ button5;
        private: ::Windows::UI::Xaml::Controls::Button^ button3;
        private: ::Windows::UI::Xaml::Controls::Button^ button10;
        private: ::Windows::UI::Xaml::Controls::Button^ button18;
        private: ::Windows::UI::Xaml::Controls::Button^ button8;
        private: ::Windows::UI::Xaml::Controls::Button^ button12;
        private: ::Windows::UI::Xaml::Controls::Button^ button17;
        private: ::Windows::UI::Xaml::Controls::Button^ button15;
        private: ::Windows::UI::Xaml::Controls::Button^ button11;
        private: ::Windows::UI::Xaml::Controls::Button^ button6;
        private: ::Windows::UI::Xaml::Controls::Image^ image1_1;
        private: ::Windows::UI::Xaml::Controls::Image^ image1_2;
        private: ::Windows::UI::Xaml::Controls::Image^ image1_3;
        private: ::Windows::UI::Xaml::Controls::Image^ image1_4;
        private: ::Windows::UI::Xaml::Controls::Image^ image2_1;
        private: ::Windows::UI::Xaml::Controls::Image^ image2_2;
        private: ::Windows::UI::Xaml::Controls::Image^ image2_3;
        private: ::Windows::UI::Xaml::Controls::Image^ image2_4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ R1;
        private: ::Windows::UI::Xaml::Controls::Image^ imagep1;
        private: ::Windows::UI::Xaml::Controls::Image^ imagep2;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ mediaElementk;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ mediaElementm;
    };
}

