#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}

namespace Strategify
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class North : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Image^ board;
        private: ::Windows::UI::Xaml::Controls::Button^ button00;
        private: ::Windows::UI::Xaml::Controls::Button^ button01;
        private: ::Windows::UI::Xaml::Controls::Button^ button02;
        private: ::Windows::UI::Xaml::Controls::Button^ button03;
        private: ::Windows::UI::Xaml::Controls::Button^ button04;
        private: ::Windows::UI::Xaml::Controls::Button^ button05;
        private: ::Windows::UI::Xaml::Controls::Button^ button06;
        private: ::Windows::UI::Xaml::Controls::Button^ button07;
        private: ::Windows::UI::Xaml::Controls::Button^ button08;
        private: ::Windows::UI::Xaml::Controls::Button^ button09;
        private: ::Windows::UI::Xaml::Controls::Button^ button010;
        private: ::Windows::UI::Xaml::Controls::Button^ button10;
        private: ::Windows::UI::Xaml::Controls::Button^ button11;
        private: ::Windows::UI::Xaml::Controls::Button^ button12;
        private: ::Windows::UI::Xaml::Controls::Button^ button13;
        private: ::Windows::UI::Xaml::Controls::Button^ button14;
        private: ::Windows::UI::Xaml::Controls::Button^ button15;
        private: ::Windows::UI::Xaml::Controls::Button^ button16;
        private: ::Windows::UI::Xaml::Controls::Button^ button17;
        private: ::Windows::UI::Xaml::Controls::Button^ button18;
        private: ::Windows::UI::Xaml::Controls::Button^ button19;
        private: ::Windows::UI::Xaml::Controls::Button^ button110;
        private: ::Windows::UI::Xaml::Controls::Button^ button20;
        private: ::Windows::UI::Xaml::Controls::Button^ button21;
        private: ::Windows::UI::Xaml::Controls::Button^ button22;
        private: ::Windows::UI::Xaml::Controls::Button^ button23;
        private: ::Windows::UI::Xaml::Controls::Button^ button24;
        private: ::Windows::UI::Xaml::Controls::Button^ button25;
        private: ::Windows::UI::Xaml::Controls::Button^ button26;
        private: ::Windows::UI::Xaml::Controls::Button^ button27;
        private: ::Windows::UI::Xaml::Controls::Button^ button28;
        private: ::Windows::UI::Xaml::Controls::Button^ button29;
        private: ::Windows::UI::Xaml::Controls::Button^ button210;
        private: ::Windows::UI::Xaml::Controls::Button^ button30;
        private: ::Windows::UI::Xaml::Controls::Button^ button31;
        private: ::Windows::UI::Xaml::Controls::Button^ button32;
        private: ::Windows::UI::Xaml::Controls::Button^ button33;
        private: ::Windows::UI::Xaml::Controls::Button^ button34;
        private: ::Windows::UI::Xaml::Controls::Button^ button35;
        private: ::Windows::UI::Xaml::Controls::Button^ button36;
        private: ::Windows::UI::Xaml::Controls::Button^ button37;
        private: ::Windows::UI::Xaml::Controls::Button^ button38;
        private: ::Windows::UI::Xaml::Controls::Button^ button39;
        private: ::Windows::UI::Xaml::Controls::Button^ button310;
        private: ::Windows::UI::Xaml::Controls::Button^ button40;
        private: ::Windows::UI::Xaml::Controls::Button^ button41;
        private: ::Windows::UI::Xaml::Controls::Button^ button42;
        private: ::Windows::UI::Xaml::Controls::Button^ button43;
        private: ::Windows::UI::Xaml::Controls::Button^ button44;
        private: ::Windows::UI::Xaml::Controls::Button^ button45;
        private: ::Windows::UI::Xaml::Controls::Button^ button46;
        private: ::Windows::UI::Xaml::Controls::Button^ button47;
        private: ::Windows::UI::Xaml::Controls::Button^ button48;
        private: ::Windows::UI::Xaml::Controls::Button^ button49;
        private: ::Windows::UI::Xaml::Controls::Button^ button410;
        private: ::Windows::UI::Xaml::Controls::Button^ button50;
        private: ::Windows::UI::Xaml::Controls::Button^ button51;
        private: ::Windows::UI::Xaml::Controls::Button^ button52;
        private: ::Windows::UI::Xaml::Controls::Button^ button53;
        private: ::Windows::UI::Xaml::Controls::Button^ button54;
        private: ::Windows::UI::Xaml::Controls::Button^ button55;
        private: ::Windows::UI::Xaml::Controls::Button^ button56;
        private: ::Windows::UI::Xaml::Controls::Button^ button57;
        private: ::Windows::UI::Xaml::Controls::Button^ button58;
        private: ::Windows::UI::Xaml::Controls::Button^ button59;
        private: ::Windows::UI::Xaml::Controls::Button^ button510;
        private: ::Windows::UI::Xaml::Controls::Button^ button60;
        private: ::Windows::UI::Xaml::Controls::Button^ button61;
        private: ::Windows::UI::Xaml::Controls::Button^ button62;
        private: ::Windows::UI::Xaml::Controls::Button^ button63;
        private: ::Windows::UI::Xaml::Controls::Button^ button64;
        private: ::Windows::UI::Xaml::Controls::Button^ button65;
        private: ::Windows::UI::Xaml::Controls::Button^ button66;
        private: ::Windows::UI::Xaml::Controls::Button^ button67;
        private: ::Windows::UI::Xaml::Controls::Button^ button68;
        private: ::Windows::UI::Xaml::Controls::Button^ button69;
        private: ::Windows::UI::Xaml::Controls::Button^ button610;
        private: ::Windows::UI::Xaml::Controls::Button^ button70;
        private: ::Windows::UI::Xaml::Controls::Button^ button71;
        private: ::Windows::UI::Xaml::Controls::Button^ button72;
        private: ::Windows::UI::Xaml::Controls::Button^ button73;
        private: ::Windows::UI::Xaml::Controls::Button^ button74;
        private: ::Windows::UI::Xaml::Controls::Button^ button75;
        private: ::Windows::UI::Xaml::Controls::Button^ button76;
        private: ::Windows::UI::Xaml::Controls::Button^ button77;
        private: ::Windows::UI::Xaml::Controls::Button^ button78;
        private: ::Windows::UI::Xaml::Controls::Button^ button79;
        private: ::Windows::UI::Xaml::Controls::Button^ button710;
        private: ::Windows::UI::Xaml::Controls::Button^ button80;
        private: ::Windows::UI::Xaml::Controls::Button^ button81;
        private: ::Windows::UI::Xaml::Controls::Button^ button82;
        private: ::Windows::UI::Xaml::Controls::Button^ button83;
        private: ::Windows::UI::Xaml::Controls::Button^ button84;
        private: ::Windows::UI::Xaml::Controls::Button^ button85;
        private: ::Windows::UI::Xaml::Controls::Button^ button86;
        private: ::Windows::UI::Xaml::Controls::Button^ button87;
        private: ::Windows::UI::Xaml::Controls::Button^ button88;
        private: ::Windows::UI::Xaml::Controls::Button^ button89;
        private: ::Windows::UI::Xaml::Controls::Button^ button810;
        private: ::Windows::UI::Xaml::Controls::Button^ button90;
        private: ::Windows::UI::Xaml::Controls::Button^ button91;
        private: ::Windows::UI::Xaml::Controls::Button^ button92;
        private: ::Windows::UI::Xaml::Controls::Button^ button93;
        private: ::Windows::UI::Xaml::Controls::Button^ button94;
        private: ::Windows::UI::Xaml::Controls::Button^ button95;
        private: ::Windows::UI::Xaml::Controls::Button^ button96;
        private: ::Windows::UI::Xaml::Controls::Button^ button97;
        private: ::Windows::UI::Xaml::Controls::Button^ button98;
        private: ::Windows::UI::Xaml::Controls::Button^ button99;
        private: ::Windows::UI::Xaml::Controls::Button^ button910;
        private: ::Windows::UI::Xaml::Controls::Button^ button;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human0;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human1;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human2;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human3;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human4;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human5;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human6;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human7;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human8;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human9;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer0;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer1;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer2;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer3;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer4;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer5;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer6;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer7;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer8;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer9;
    };
}

