//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::App2::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::App2::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->image = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 2:
            {
                this->board = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 3:
            {
                this->image11 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 4:
            {
                this->image12 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 5:
            {
                this->image13 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 6:
            {
                this->image14 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 7:
            {
                this->image15 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 8:
            {
                this->image16 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 9:
            {
                this->image17 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 10:
            {
                this->image18 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 11:
            {
                this->image19 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 12:
            {
                this->image21 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 13:
            {
                this->image22 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 14:
            {
                this->image23 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 15:
            {
                this->image24 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 16:
            {
                this->image25 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 17:
            {
                this->image26 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 18:
            {
                this->image27 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 19:
            {
                this->image28 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 20:
            {
                this->image29 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 21:
            {
                this->button0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button_Click);
            }
            break;
        case 22:
            {
                this->button1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button1_Click);
            }
            break;
        case 23:
            {
                this->button2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button2_Click);
            }
            break;
        case 24:
            {
                this->button9 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button9))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button9_Click);
            }
            break;
        case 25:
            {
                this->button21 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button21))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button21_Click);
            }
            break;
        case 26:
            {
                this->button22 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button22))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button22_Click);
            }
            break;
        case 27:
            {
                this->button23 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button23))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button23_Click);
            }
            break;
        case 28:
            {
                this->button14 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button14))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button14_Click);
            }
            break;
        case 29:
            {
                this->button4 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button4))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button4_Click);
            }
            break;
        case 30:
            {
                this->button7 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button7))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button7_Click);
            }
            break;
        case 31:
            {
                this->button16 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button16))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button16_Click);
            }
            break;
        case 32:
            {
                this->button19 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button19))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button19_Click);
            }
            break;
        case 33:
            {
                this->button20 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button20))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button20_Click);
            }
            break;
        case 34:
            {
                this->button13 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button13))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button13_Click);
            }
            break;
        case 35:
            {
                this->button5 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button5))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button5_Click);
            }
            break;
        case 36:
            {
                this->button3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button3_Click);
            }
            break;
        case 37:
            {
                this->button10 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button10))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button10_Click);
            }
            break;
        case 38:
            {
                this->button18 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button18))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button18_Click);
            }
            break;
        case 39:
            {
                this->button8 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button8))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button8_Click);
            }
            break;
        case 40:
            {
                this->button12 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button12))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button12_Click);
            }
            break;
        case 41:
            {
                this->button17 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button17))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button17_Click);
            }
            break;
        case 42:
            {
                this->button15 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button15))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button15_Click);
            }
            break;
        case 43:
            {
                this->button11 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button11))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button11_Click);
            }
            break;
        case 44:
            {
                this->button6 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button6))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button6_Click);
            }
            break;
        case 45:
            {
                this->image1_1 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 46:
            {
                this->image1_2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 47:
            {
                this->image1_3 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 48:
            {
                this->image1_4 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 49:
            {
                this->image2_1 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 50:
            {
                this->image2_2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 51:
            {
                this->image2_3 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 52:
            {
                this->image2_4 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 53:
            {
                this->R1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
            }
            break;
        case 54:
            {
                this->imagep1 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 55:
            {
                this->imagep2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 56:
            {
                this->mediaElementk = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 57:
            {
                this->mediaElementm = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::App2::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


