#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class Button;
                ref class MediaElement;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace App2
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage1 : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Image^ image;
        private: ::Windows::UI::Xaml::Controls::Image^ board;
        private: ::Windows::UI::Xaml::Controls::Image^ image111;
        private: ::Windows::UI::Xaml::Controls::Image^ image121;
        private: ::Windows::UI::Xaml::Controls::Image^ image131;
        private: ::Windows::UI::Xaml::Controls::Image^ image141;
        private: ::Windows::UI::Xaml::Controls::Image^ image151;
        private: ::Windows::UI::Xaml::Controls::Image^ image161;
        private: ::Windows::UI::Xaml::Controls::Image^ image171;
        private: ::Windows::UI::Xaml::Controls::Image^ image181;
        private: ::Windows::UI::Xaml::Controls::Image^ image191;
        private: ::Windows::UI::Xaml::Controls::Image^ image211;
        private: ::Windows::UI::Xaml::Controls::Image^ image221;
        private: ::Windows::UI::Xaml::Controls::Image^ image231;
        private: ::Windows::UI::Xaml::Controls::Image^ image241;
        private: ::Windows::UI::Xaml::Controls::Image^ image251;
        private: ::Windows::UI::Xaml::Controls::Image^ image261;
        private: ::Windows::UI::Xaml::Controls::Image^ image271;
        private: ::Windows::UI::Xaml::Controls::Image^ image281;
        private: ::Windows::UI::Xaml::Controls::Image^ image291;
        private: ::Windows::UI::Xaml::Controls::Button^ button01;
        private: ::Windows::UI::Xaml::Controls::Button^ button11;
        private: ::Windows::UI::Xaml::Controls::Button^ button21;
        private: ::Windows::UI::Xaml::Controls::Button^ button91;
        private: ::Windows::UI::Xaml::Controls::Button^ button211;
        private: ::Windows::UI::Xaml::Controls::Button^ button221;
        private: ::Windows::UI::Xaml::Controls::Button^ button231;
        private: ::Windows::UI::Xaml::Controls::Button^ button141;
        private: ::Windows::UI::Xaml::Controls::Button^ button41;
        private: ::Windows::UI::Xaml::Controls::Button^ button71;
        private: ::Windows::UI::Xaml::Controls::Button^ button161;
        private: ::Windows::UI::Xaml::Controls::Button^ button191;
        private: ::Windows::UI::Xaml::Controls::Button^ button201;
        private: ::Windows::UI::Xaml::Controls::Button^ button131;
        private: ::Windows::UI::Xaml::Controls::Button^ button51;
        private: ::Windows::UI::Xaml::Controls::Button^ button31;
        private: ::Windows::UI::Xaml::Controls::Button^ button101;
        private: ::Windows::UI::Xaml::Controls::Button^ button181;
        private: ::Windows::UI::Xaml::Controls::Button^ button81;
        private: ::Windows::UI::Xaml::Controls::Button^ button121;
        private: ::Windows::UI::Xaml::Controls::Button^ button171;
        private: ::Windows::UI::Xaml::Controls::Button^ button151;
        private: ::Windows::UI::Xaml::Controls::Button^ button111;
        private: ::Windows::UI::Xaml::Controls::Button^ button61;
        private: ::Windows::UI::Xaml::Controls::Image^ image1_11;
        private: ::Windows::UI::Xaml::Controls::Image^ image1_21;
        private: ::Windows::UI::Xaml::Controls::Image^ image1_31;
        private: ::Windows::UI::Xaml::Controls::Image^ image1_41;
        private: ::Windows::UI::Xaml::Controls::Image^ image2_11;
        private: ::Windows::UI::Xaml::Controls::Image^ image2_21;
        private: ::Windows::UI::Xaml::Controls::Image^ image2_31;
        private: ::Windows::UI::Xaml::Controls::Image^ image2_41;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ R1x;
        private: ::Windows::UI::Xaml::Controls::Image^ imagep1x;
        private: ::Windows::UI::Xaml::Controls::Image^ imagep2x;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ mediaElementf;
    };
}

