//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "North1.xaml.h"

void ::App2::North1::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///North1.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::App2::North1::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->image3 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 2:
            {
                this->board3 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 3:
            {
                this->button003 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button003))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button00_Click3);
            }
            break;
        case 4:
            {
                this->button013 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button013))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button01_Click3);
            }
            break;
        case 5:
            {
                this->button023 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button023))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button02_Click3);
            }
            break;
        case 6:
            {
                this->button033 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button033))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button03_Click3);
            }
            break;
        case 7:
            {
                this->button043 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button043))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button04_Click3);
            }
            break;
        case 8:
            {
                this->button053 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button053))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button05_Click3);
            }
            break;
        case 9:
            {
                this->button063 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button063))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button06_Click3);
            }
            break;
        case 10:
            {
                this->button073 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button073))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button07_Click3);
            }
            break;
        case 11:
            {
                this->button083 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button083))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button08_Click3);
            }
            break;
        case 12:
            {
                this->button093 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button093))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button09_Click3);
            }
            break;
        case 13:
            {
                this->button0103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button0103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button010_Click3);
            }
            break;
        case 14:
            {
                this->button103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button10_Click3);
            }
            break;
        case 15:
            {
                this->button113 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button113))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button11_Click3);
            }
            break;
        case 16:
            {
                this->button123 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button123))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button12_Click3);
            }
            break;
        case 17:
            {
                this->button133 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button133))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button13_Click3);
            }
            break;
        case 18:
            {
                this->button143 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button143))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button14_Click3);
            }
            break;
        case 19:
            {
                this->button153 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button153))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button15_Click3);
            }
            break;
        case 20:
            {
                this->button163 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button163))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button16_Click3);
            }
            break;
        case 21:
            {
                this->button173 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button173))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button17_Click3);
            }
            break;
        case 22:
            {
                this->button183 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button183))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button18_Click3);
            }
            break;
        case 23:
            {
                this->button193 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button193))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button19_Click3);
            }
            break;
        case 24:
            {
                this->button1103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button1103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button110_Click3);
            }
            break;
        case 25:
            {
                this->button203 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button203))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button20_Click3);
            }
            break;
        case 26:
            {
                this->button213 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button213))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button21_Click3);
            }
            break;
        case 27:
            {
                this->button223 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button223))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button22_Click3);
            }
            break;
        case 28:
            {
                this->button233 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button233))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button23_Click3);
            }
            break;
        case 29:
            {
                this->button243 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button243))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button24_Click3);
            }
            break;
        case 30:
            {
                this->button253 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button253))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button25_Click3);
            }
            break;
        case 31:
            {
                this->button263 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button263))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button26_Click3);
            }
            break;
        case 32:
            {
                this->button273 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button273))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button27_Click3);
            }
            break;
        case 33:
            {
                this->button283 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button283))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button28_Click3);
            }
            break;
        case 34:
            {
                this->button293 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button293))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button29_Click3);
            }
            break;
        case 35:
            {
                this->button2103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button2103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button210_Click3);
            }
            break;
        case 36:
            {
                this->button303 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button303))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button30_Click3);
            }
            break;
        case 37:
            {
                this->button313 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button313))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button31_Click3);
            }
            break;
        case 38:
            {
                this->button323 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button323))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button32_Click3);
            }
            break;
        case 39:
            {
                this->button333 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button333))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button33_Click3);
            }
            break;
        case 40:
            {
                this->button343 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button343))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button34_Click3);
            }
            break;
        case 41:
            {
                this->button353 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button353))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button35_Click3);
            }
            break;
        case 42:
            {
                this->button363 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button363))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button36_Click3);
            }
            break;
        case 43:
            {
                this->button373 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button373))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button37_Click3);
            }
            break;
        case 44:
            {
                this->button383 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button383))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button38_Click3);
            }
            break;
        case 45:
            {
                this->button393 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button393))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button39_Click3);
            }
            break;
        case 46:
            {
                this->button3103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button3103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button310_Click3);
            }
            break;
        case 47:
            {
                this->button403 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button403))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button40_Click3);
            }
            break;
        case 48:
            {
                this->button413 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button413))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button41_Click3);
            }
            break;
        case 49:
            {
                this->button423 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button423))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button42_Click3);
            }
            break;
        case 50:
            {
                this->button433 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button433))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button43_Click3);
            }
            break;
        case 51:
            {
                this->button443 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button443))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button44_Click3);
            }
            break;
        case 52:
            {
                this->button453 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button453))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button45_Click3);
            }
            break;
        case 53:
            {
                this->button463 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button463))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button46_Click3);
            }
            break;
        case 54:
            {
                this->button473 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button473))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button47_Click3);
            }
            break;
        case 55:
            {
                this->button483 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button483))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button48_Click3);
            }
            break;
        case 56:
            {
                this->button493 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button493))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button49_Click3);
            }
            break;
        case 57:
            {
                this->button4103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button4103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button410_Click3);
            }
            break;
        case 58:
            {
                this->button503 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button503))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button50_Click3);
            }
            break;
        case 59:
            {
                this->button513 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button513))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button51_Click3);
            }
            break;
        case 60:
            {
                this->button523 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button523))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button52_Click3);
            }
            break;
        case 61:
            {
                this->button533 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button533))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button53_Click3);
            }
            break;
        case 62:
            {
                this->button543 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button543))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button54_Click3);
            }
            break;
        case 63:
            {
                this->button553 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button553))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button55_Click3);
            }
            break;
        case 64:
            {
                this->button563 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button563))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button56_Click3);
            }
            break;
        case 65:
            {
                this->button573 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button573))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button57_Click3);
            }
            break;
        case 66:
            {
                this->button583 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button583))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button58_Click3);
            }
            break;
        case 67:
            {
                this->button593 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button593))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button59_Click3);
            }
            break;
        case 68:
            {
                this->button5103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button5103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button510_Click3);
            }
            break;
        case 69:
            {
                this->button603 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button603))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button60_Click3);
            }
            break;
        case 70:
            {
                this->button613 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button613))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button61_Click3);
            }
            break;
        case 71:
            {
                this->button623 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button623))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button62_Click3);
            }
            break;
        case 72:
            {
                this->button633 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button633))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button63_Click3);
            }
            break;
        case 73:
            {
                this->button643 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button643))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button64_Click3);
            }
            break;
        case 74:
            {
                this->button653 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button653))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button65_Click3);
            }
            break;
        case 75:
            {
                this->button663 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button663))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button66_Click3);
            }
            break;
        case 76:
            {
                this->button673 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button673))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button67_Click3);
            }
            break;
        case 77:
            {
                this->button683 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button683))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button68_Click3);
            }
            break;
        case 78:
            {
                this->button693 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button693))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button69_Click3);
            }
            break;
        case 79:
            {
                this->button6103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button6103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button610_Click3);
            }
            break;
        case 80:
            {
                this->button703 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button703))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button70_Click3);
            }
            break;
        case 81:
            {
                this->button713 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button713))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button71_Click3);
            }
            break;
        case 82:
            {
                this->button723 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button723))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button72_Click3);
            }
            break;
        case 83:
            {
                this->button733 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button733))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button73_Click3);
            }
            break;
        case 84:
            {
                this->button743 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button743))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button74_Click3);
            }
            break;
        case 85:
            {
                this->button753 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button753))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button75_Click3);
            }
            break;
        case 86:
            {
                this->button763 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button763))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button76_Click3);
            }
            break;
        case 87:
            {
                this->button773 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button773))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button77_Click3);
            }
            break;
        case 88:
            {
                this->button783 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button783))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button78_Click3);
            }
            break;
        case 89:
            {
                this->button793 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button793))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button79_Click3);
            }
            break;
        case 90:
            {
                this->button7103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button7103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button710_Click3);
            }
            break;
        case 91:
            {
                this->button803 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button803))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button80_Click3);
            }
            break;
        case 92:
            {
                this->button813 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button813))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button81_Click3);
            }
            break;
        case 93:
            {
                this->button823 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button823))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button82_Click3);
            }
            break;
        case 94:
            {
                this->button833 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button833))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button83_Click3);
            }
            break;
        case 95:
            {
                this->button843 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button843))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button84_Click3);
            }
            break;
        case 96:
            {
                this->button853 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button853))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button85_Click3);
            }
            break;
        case 97:
            {
                this->button863 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button863))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button86_Click3);
            }
            break;
        case 98:
            {
                this->button873 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button873))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button87_Click3);
            }
            break;
        case 99:
            {
                this->button883 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button883))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button88_Click3);
            }
            break;
        case 100:
            {
                this->button893 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button893))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button89_Click3);
            }
            break;
        case 101:
            {
                this->button8103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button8103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button810_Click3);
            }
            break;
        case 102:
            {
                this->button903 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button903))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button90_Click3);
            }
            break;
        case 103:
            {
                this->button913 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button913))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button91_Click3);
            }
            break;
        case 104:
            {
                this->button923 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button923))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button92_Click3);
            }
            break;
        case 105:
            {
                this->button933 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button933))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button93_Click3);
            }
            break;
        case 106:
            {
                this->button943 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button943))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button94_Click3);
            }
            break;
        case 107:
            {
                this->button953 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button953))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button95_Click3);
            }
            break;
        case 108:
            {
                this->button963 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button963))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button96_Click3);
            }
            break;
        case 109:
            {
                this->button973 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button973))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button97_Click3);
            }
            break;
        case 110:
            {
                this->button983 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button983))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button98_Click3);
            }
            break;
        case 111:
            {
                this->button993 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button993))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button99_Click3);
            }
            break;
        case 112:
            {
                this->button9103 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button9103))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button910_Click3);
            }
            break;
        case 113:
            {
                this->button3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button_Click3);
            }
            break;
        case 114:
            {
                this->image_human03 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 115:
            {
                this->image_human13 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 116:
            {
                this->image_human23 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 117:
            {
                this->image_human33 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 118:
            {
                this->image_human43 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 119:
            {
                this->image_human53 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 120:
            {
                this->image_human63 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 121:
            {
                this->image_human73 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 122:
            {
                this->image_human83 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 123:
            {
                this->image_human93 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 124:
            {
                this->image_computer03 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 125:
            {
                this->image_computer13 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 126:
            {
                this->image_computer23 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 127:
            {
                this->image_computer33 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 128:
            {
                this->image_computer43 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 129:
            {
                this->image_computer53 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 130:
            {
                this->image_computer63 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 131:
            {
                this->image_computer73 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 132:
            {
                this->image_computer83 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 133:
            {
                this->image_computer93 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 134:
            {
                this->quote13 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 135:
            {
                this->quote23 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 136:
            {
                this->quote33 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 137:
            {
                this->quote43 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 138:
            {
                this->quote53 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 139:
            {
                this->quote63 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 140:
            {
                this->quote73 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 141:
            {
                this->quote83 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 142:
            {
                this->button13 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button13))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North1::button1_Click3);
            }
            break;
        case 143:
            {
                this->R1z = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
            }
            break;
        case 144:
            {
                this->imagep1z = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 145:
            {
                this->imagep2z = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::App2::North1::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


