//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "North.xaml.h"

void ::App2::North::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///North.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::App2::North::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->image = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 2:
            {
                this->board = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 3:
            {
                this->button00 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button00))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button00_Click);
            }
            break;
        case 4:
            {
                this->button01 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button01))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button01_Click);
            }
            break;
        case 5:
            {
                this->button02 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button02))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button02_Click);
            }
            break;
        case 6:
            {
                this->button03 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button03))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button03_Click);
            }
            break;
        case 7:
            {
                this->button04 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button04))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button04_Click);
            }
            break;
        case 8:
            {
                this->button05 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button05))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button05_Click);
            }
            break;
        case 9:
            {
                this->button06 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button06))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button06_Click);
            }
            break;
        case 10:
            {
                this->button07 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button07))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button07_Click);
            }
            break;
        case 11:
            {
                this->button08 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button08))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button08_Click);
            }
            break;
        case 12:
            {
                this->button09 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button09))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button09_Click);
            }
            break;
        case 13:
            {
                this->button010 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button010))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button010_Click);
            }
            break;
        case 14:
            {
                this->button10 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button10))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button10_Click);
            }
            break;
        case 15:
            {
                this->button11 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button11))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button11_Click);
            }
            break;
        case 16:
            {
                this->button12 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button12))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button12_Click);
            }
            break;
        case 17:
            {
                this->button13 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button13))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button13_Click);
            }
            break;
        case 18:
            {
                this->button14 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button14))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button14_Click);
            }
            break;
        case 19:
            {
                this->button15 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button15))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button15_Click);
            }
            break;
        case 20:
            {
                this->button16 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button16))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button16_Click);
            }
            break;
        case 21:
            {
                this->button17 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button17))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button17_Click);
            }
            break;
        case 22:
            {
                this->button18 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button18))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button18_Click);
            }
            break;
        case 23:
            {
                this->button19 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button19))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button19_Click);
            }
            break;
        case 24:
            {
                this->button110 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button110))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button110_Click);
            }
            break;
        case 25:
            {
                this->button20 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button20))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button20_Click);
            }
            break;
        case 26:
            {
                this->button21 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button21))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button21_Click);
            }
            break;
        case 27:
            {
                this->button22 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button22))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button22_Click);
            }
            break;
        case 28:
            {
                this->button23 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button23))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button23_Click);
            }
            break;
        case 29:
            {
                this->button24 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button24))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button24_Click);
            }
            break;
        case 30:
            {
                this->button25 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button25))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button25_Click);
            }
            break;
        case 31:
            {
                this->button26 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button26))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button26_Click);
            }
            break;
        case 32:
            {
                this->button27 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button27))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button27_Click);
            }
            break;
        case 33:
            {
                this->button28 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button28))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button28_Click);
            }
            break;
        case 34:
            {
                this->button29 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button29))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button29_Click);
            }
            break;
        case 35:
            {
                this->button210 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button210))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button210_Click);
            }
            break;
        case 36:
            {
                this->button30 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button30))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button30_Click);
            }
            break;
        case 37:
            {
                this->button31 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button31))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button31_Click);
            }
            break;
        case 38:
            {
                this->button32 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button32))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button32_Click);
            }
            break;
        case 39:
            {
                this->button33 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button33))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button33_Click);
            }
            break;
        case 40:
            {
                this->button34 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button34))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button34_Click);
            }
            break;
        case 41:
            {
                this->button35 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button35))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button35_Click);
            }
            break;
        case 42:
            {
                this->button36 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button36))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button36_Click);
            }
            break;
        case 43:
            {
                this->button37 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button37))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button37_Click);
            }
            break;
        case 44:
            {
                this->button38 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button38))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button38_Click);
            }
            break;
        case 45:
            {
                this->button39 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button39))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button39_Click);
            }
            break;
        case 46:
            {
                this->button310 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button310))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button310_Click);
            }
            break;
        case 47:
            {
                this->button40 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button40))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button40_Click);
            }
            break;
        case 48:
            {
                this->button41 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button41))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button41_Click);
            }
            break;
        case 49:
            {
                this->button42 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button42))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button42_Click);
            }
            break;
        case 50:
            {
                this->button43 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button43))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button43_Click);
            }
            break;
        case 51:
            {
                this->button44 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button44))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button44_Click);
            }
            break;
        case 52:
            {
                this->button45 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button45))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button45_Click);
            }
            break;
        case 53:
            {
                this->button46 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button46))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button46_Click);
            }
            break;
        case 54:
            {
                this->button47 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button47))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button47_Click);
            }
            break;
        case 55:
            {
                this->button48 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button48))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button48_Click);
            }
            break;
        case 56:
            {
                this->button49 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button49))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button49_Click);
            }
            break;
        case 57:
            {
                this->button410 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button410))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button410_Click);
            }
            break;
        case 58:
            {
                this->button50 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button50))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button50_Click);
            }
            break;
        case 59:
            {
                this->button51 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button51))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button51_Click);
            }
            break;
        case 60:
            {
                this->button52 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button52))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button52_Click);
            }
            break;
        case 61:
            {
                this->button53 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button53))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button53_Click);
            }
            break;
        case 62:
            {
                this->button54 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button54))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button54_Click);
            }
            break;
        case 63:
            {
                this->button55 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button55))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button55_Click);
            }
            break;
        case 64:
            {
                this->button56 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button56))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button56_Click);
            }
            break;
        case 65:
            {
                this->button57 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button57))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button57_Click);
            }
            break;
        case 66:
            {
                this->button58 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button58))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button58_Click);
            }
            break;
        case 67:
            {
                this->button59 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button59))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button59_Click);
            }
            break;
        case 68:
            {
                this->button510 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button510))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button510_Click);
            }
            break;
        case 69:
            {
                this->button60 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button60))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button60_Click);
            }
            break;
        case 70:
            {
                this->button61 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button61))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button61_Click);
            }
            break;
        case 71:
            {
                this->button62 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button62))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button62_Click);
            }
            break;
        case 72:
            {
                this->button63 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button63))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button63_Click);
            }
            break;
        case 73:
            {
                this->button64 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button64))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button64_Click);
            }
            break;
        case 74:
            {
                this->button65 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button65))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button65_Click);
            }
            break;
        case 75:
            {
                this->button66 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button66))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button66_Click);
            }
            break;
        case 76:
            {
                this->button67 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button67))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button67_Click);
            }
            break;
        case 77:
            {
                this->button68 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button68))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button68_Click);
            }
            break;
        case 78:
            {
                this->button69 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button69))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button69_Click);
            }
            break;
        case 79:
            {
                this->button610 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button610))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button610_Click);
            }
            break;
        case 80:
            {
                this->button70 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button70))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button70_Click);
            }
            break;
        case 81:
            {
                this->button71 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button71))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button71_Click);
            }
            break;
        case 82:
            {
                this->button72 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button72))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button72_Click);
            }
            break;
        case 83:
            {
                this->button73 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button73))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button73_Click);
            }
            break;
        case 84:
            {
                this->button74 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button74))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button74_Click);
            }
            break;
        case 85:
            {
                this->button75 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button75))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button75_Click);
            }
            break;
        case 86:
            {
                this->button76 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button76))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button76_Click);
            }
            break;
        case 87:
            {
                this->button77 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button77))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button77_Click);
            }
            break;
        case 88:
            {
                this->button78 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button78))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button78_Click);
            }
            break;
        case 89:
            {
                this->button79 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button79))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button79_Click);
            }
            break;
        case 90:
            {
                this->button710 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button710))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button710_Click);
            }
            break;
        case 91:
            {
                this->button80 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button80))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button80_Click);
            }
            break;
        case 92:
            {
                this->button81 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button81))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button81_Click);
            }
            break;
        case 93:
            {
                this->button82 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button82))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button82_Click);
            }
            break;
        case 94:
            {
                this->button83 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button83))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button83_Click);
            }
            break;
        case 95:
            {
                this->button84 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button84))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button84_Click);
            }
            break;
        case 96:
            {
                this->button85 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button85))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button85_Click);
            }
            break;
        case 97:
            {
                this->button86 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button86))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button86_Click);
            }
            break;
        case 98:
            {
                this->button87 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button87))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button87_Click);
            }
            break;
        case 99:
            {
                this->button88 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button88))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button88_Click);
            }
            break;
        case 100:
            {
                this->button89 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button89))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button89_Click);
            }
            break;
        case 101:
            {
                this->button810 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button810))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button810_Click);
            }
            break;
        case 102:
            {
                this->button90 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button90))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button90_Click);
            }
            break;
        case 103:
            {
                this->button91 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button91))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button91_Click);
            }
            break;
        case 104:
            {
                this->button92 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button92))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button92_Click);
            }
            break;
        case 105:
            {
                this->button93 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button93))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button93_Click);
            }
            break;
        case 106:
            {
                this->button94 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button94))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button94_Click);
            }
            break;
        case 107:
            {
                this->button95 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button95))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button95_Click);
            }
            break;
        case 108:
            {
                this->button96 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button96))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button96_Click);
            }
            break;
        case 109:
            {
                this->button97 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button97))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button97_Click);
            }
            break;
        case 110:
            {
                this->button98 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button98))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button98_Click);
            }
            break;
        case 111:
            {
                this->button99 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button99))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button99_Click);
            }
            break;
        case 112:
            {
                this->button910 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button910))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button910_Click);
            }
            break;
        case 113:
            {
                this->button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button_Click);
            }
            break;
        case 114:
            {
                this->image_human0 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 115:
            {
                this->image_human1 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 116:
            {
                this->image_human2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 117:
            {
                this->image_human3 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 118:
            {
                this->image_human4 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 119:
            {
                this->image_human5 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 120:
            {
                this->image_human6 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 121:
            {
                this->image_human7 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 122:
            {
                this->image_human8 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 123:
            {
                this->image_human9 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 124:
            {
                this->image_computer0 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 125:
            {
                this->image_computer1 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 126:
            {
                this->image_computer2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 127:
            {
                this->image_computer3 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 128:
            {
                this->image_computer4 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 129:
            {
                this->image_computer5 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 130:
            {
                this->image_computer6 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 131:
            {
                this->image_computer7 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 132:
            {
                this->image_computer8 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 133:
            {
                this->image_computer9 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 134:
            {
                this->quote1 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 135:
            {
                this->quote2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 136:
            {
                this->quote3 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 137:
            {
                this->quote4 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 138:
            {
                this->quote5 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 139:
            {
                this->quote6 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 140:
            {
                this->quote7 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 141:
            {
                this->quote8 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 142:
            {
                this->button1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::North::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&North::button1_Click);
            }
            break;
        case 143:
            {
                this->R1y = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
            }
            break;
        case 144:
            {
                this->imagep1y = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 145:
            {
                this->imagep2y = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::App2::North::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


