#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class Button;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace App2
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class North1 : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Image^ image3;
        private: ::Windows::UI::Xaml::Controls::Image^ board3;
        private: ::Windows::UI::Xaml::Controls::Button^ button003;
        private: ::Windows::UI::Xaml::Controls::Button^ button013;
        private: ::Windows::UI::Xaml::Controls::Button^ button023;
        private: ::Windows::UI::Xaml::Controls::Button^ button033;
        private: ::Windows::UI::Xaml::Controls::Button^ button043;
        private: ::Windows::UI::Xaml::Controls::Button^ button053;
        private: ::Windows::UI::Xaml::Controls::Button^ button063;
        private: ::Windows::UI::Xaml::Controls::Button^ button073;
        private: ::Windows::UI::Xaml::Controls::Button^ button083;
        private: ::Windows::UI::Xaml::Controls::Button^ button093;
        private: ::Windows::UI::Xaml::Controls::Button^ button0103;
        private: ::Windows::UI::Xaml::Controls::Button^ button103;
        private: ::Windows::UI::Xaml::Controls::Button^ button113;
        private: ::Windows::UI::Xaml::Controls::Button^ button123;
        private: ::Windows::UI::Xaml::Controls::Button^ button133;
        private: ::Windows::UI::Xaml::Controls::Button^ button143;
        private: ::Windows::UI::Xaml::Controls::Button^ button153;
        private: ::Windows::UI::Xaml::Controls::Button^ button163;
        private: ::Windows::UI::Xaml::Controls::Button^ button173;
        private: ::Windows::UI::Xaml::Controls::Button^ button183;
        private: ::Windows::UI::Xaml::Controls::Button^ button193;
        private: ::Windows::UI::Xaml::Controls::Button^ button1103;
        private: ::Windows::UI::Xaml::Controls::Button^ button203;
        private: ::Windows::UI::Xaml::Controls::Button^ button213;
        private: ::Windows::UI::Xaml::Controls::Button^ button223;
        private: ::Windows::UI::Xaml::Controls::Button^ button233;
        private: ::Windows::UI::Xaml::Controls::Button^ button243;
        private: ::Windows::UI::Xaml::Controls::Button^ button253;
        private: ::Windows::UI::Xaml::Controls::Button^ button263;
        private: ::Windows::UI::Xaml::Controls::Button^ button273;
        private: ::Windows::UI::Xaml::Controls::Button^ button283;
        private: ::Windows::UI::Xaml::Controls::Button^ button293;
        private: ::Windows::UI::Xaml::Controls::Button^ button2103;
        private: ::Windows::UI::Xaml::Controls::Button^ button303;
        private: ::Windows::UI::Xaml::Controls::Button^ button313;
        private: ::Windows::UI::Xaml::Controls::Button^ button323;
        private: ::Windows::UI::Xaml::Controls::Button^ button333;
        private: ::Windows::UI::Xaml::Controls::Button^ button343;
        private: ::Windows::UI::Xaml::Controls::Button^ button353;
        private: ::Windows::UI::Xaml::Controls::Button^ button363;
        private: ::Windows::UI::Xaml::Controls::Button^ button373;
        private: ::Windows::UI::Xaml::Controls::Button^ button383;
        private: ::Windows::UI::Xaml::Controls::Button^ button393;
        private: ::Windows::UI::Xaml::Controls::Button^ button3103;
        private: ::Windows::UI::Xaml::Controls::Button^ button403;
        private: ::Windows::UI::Xaml::Controls::Button^ button413;
        private: ::Windows::UI::Xaml::Controls::Button^ button423;
        private: ::Windows::UI::Xaml::Controls::Button^ button433;
        private: ::Windows::UI::Xaml::Controls::Button^ button443;
        private: ::Windows::UI::Xaml::Controls::Button^ button453;
        private: ::Windows::UI::Xaml::Controls::Button^ button463;
        private: ::Windows::UI::Xaml::Controls::Button^ button473;
        private: ::Windows::UI::Xaml::Controls::Button^ button483;
        private: ::Windows::UI::Xaml::Controls::Button^ button493;
        private: ::Windows::UI::Xaml::Controls::Button^ button4103;
        private: ::Windows::UI::Xaml::Controls::Button^ button503;
        private: ::Windows::UI::Xaml::Controls::Button^ button513;
        private: ::Windows::UI::Xaml::Controls::Button^ button523;
        private: ::Windows::UI::Xaml::Controls::Button^ button533;
        private: ::Windows::UI::Xaml::Controls::Button^ button543;
        private: ::Windows::UI::Xaml::Controls::Button^ button553;
        private: ::Windows::UI::Xaml::Controls::Button^ button563;
        private: ::Windows::UI::Xaml::Controls::Button^ button573;
        private: ::Windows::UI::Xaml::Controls::Button^ button583;
        private: ::Windows::UI::Xaml::Controls::Button^ button593;
        private: ::Windows::UI::Xaml::Controls::Button^ button5103;
        private: ::Windows::UI::Xaml::Controls::Button^ button603;
        private: ::Windows::UI::Xaml::Controls::Button^ button613;
        private: ::Windows::UI::Xaml::Controls::Button^ button623;
        private: ::Windows::UI::Xaml::Controls::Button^ button633;
        private: ::Windows::UI::Xaml::Controls::Button^ button643;
        private: ::Windows::UI::Xaml::Controls::Button^ button653;
        private: ::Windows::UI::Xaml::Controls::Button^ button663;
        private: ::Windows::UI::Xaml::Controls::Button^ button673;
        private: ::Windows::UI::Xaml::Controls::Button^ button683;
        private: ::Windows::UI::Xaml::Controls::Button^ button693;
        private: ::Windows::UI::Xaml::Controls::Button^ button6103;
        private: ::Windows::UI::Xaml::Controls::Button^ button703;
        private: ::Windows::UI::Xaml::Controls::Button^ button713;
        private: ::Windows::UI::Xaml::Controls::Button^ button723;
        private: ::Windows::UI::Xaml::Controls::Button^ button733;
        private: ::Windows::UI::Xaml::Controls::Button^ button743;
        private: ::Windows::UI::Xaml::Controls::Button^ button753;
        private: ::Windows::UI::Xaml::Controls::Button^ button763;
        private: ::Windows::UI::Xaml::Controls::Button^ button773;
        private: ::Windows::UI::Xaml::Controls::Button^ button783;
        private: ::Windows::UI::Xaml::Controls::Button^ button793;
        private: ::Windows::UI::Xaml::Controls::Button^ button7103;
        private: ::Windows::UI::Xaml::Controls::Button^ button803;
        private: ::Windows::UI::Xaml::Controls::Button^ button813;
        private: ::Windows::UI::Xaml::Controls::Button^ button823;
        private: ::Windows::UI::Xaml::Controls::Button^ button833;
        private: ::Windows::UI::Xaml::Controls::Button^ button843;
        private: ::Windows::UI::Xaml::Controls::Button^ button853;
        private: ::Windows::UI::Xaml::Controls::Button^ button863;
        private: ::Windows::UI::Xaml::Controls::Button^ button873;
        private: ::Windows::UI::Xaml::Controls::Button^ button883;
        private: ::Windows::UI::Xaml::Controls::Button^ button893;
        private: ::Windows::UI::Xaml::Controls::Button^ button8103;
        private: ::Windows::UI::Xaml::Controls::Button^ button903;
        private: ::Windows::UI::Xaml::Controls::Button^ button913;
        private: ::Windows::UI::Xaml::Controls::Button^ button923;
        private: ::Windows::UI::Xaml::Controls::Button^ button933;
        private: ::Windows::UI::Xaml::Controls::Button^ button943;
        private: ::Windows::UI::Xaml::Controls::Button^ button953;
        private: ::Windows::UI::Xaml::Controls::Button^ button963;
        private: ::Windows::UI::Xaml::Controls::Button^ button973;
        private: ::Windows::UI::Xaml::Controls::Button^ button983;
        private: ::Windows::UI::Xaml::Controls::Button^ button993;
        private: ::Windows::UI::Xaml::Controls::Button^ button9103;
        private: ::Windows::UI::Xaml::Controls::Button^ button3;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human03;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human13;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human23;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human33;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human43;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human53;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human63;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human73;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human83;
        private: ::Windows::UI::Xaml::Controls::Image^ image_human93;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer03;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer13;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer23;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer33;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer43;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer53;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer63;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer73;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer83;
        private: ::Windows::UI::Xaml::Controls::Image^ image_computer93;
        private: ::Windows::UI::Xaml::Controls::Image^ quote13;
        private: ::Windows::UI::Xaml::Controls::Image^ quote23;
        private: ::Windows::UI::Xaml::Controls::Image^ quote33;
        private: ::Windows::UI::Xaml::Controls::Image^ quote43;
        private: ::Windows::UI::Xaml::Controls::Image^ quote53;
        private: ::Windows::UI::Xaml::Controls::Image^ quote63;
        private: ::Windows::UI::Xaml::Controls::Image^ quote73;
        private: ::Windows::UI::Xaml::Controls::Image^ quote83;
        private: ::Windows::UI::Xaml::Controls::Button^ button13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ R1z;
        private: ::Windows::UI::Xaml::Controls::Image^ imagep1z;
        private: ::Windows::UI::Xaml::Controls::Image^ imagep2z;
    };
}

